"""tabela clientes

Revision ID: 0a9343faac8c
Revises: 29724907d252
Create Date: 2024-12-01 14:25:23.656265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9343faac8c'
down_revision: Union[str, None] = '29724907d252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('limite_de_credito', sa.Float(), nullable=False),
    sa.Column('cliente_especial', sa.Boolean(), nullable=False),
    sa.Column('periodo_pagamento', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
