"""tabela usuarios

Revision ID: 8cffad126824
Revises: 0a9343faac8c
Create Date: 2024-12-05 22:25:17.349381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cffad126824'
down_revision: Union[str, None] = '0a9343faac8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.alter_column('clientes', 'periodo_pagamento',
               existing_type=sa.VARCHAR(),
               type_=sa.Interval(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'periodo_pagamento',
               existing_type=sa.Interval(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('usuarios')
    # ### end Alembic commands ###
